name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk autoconf libtool pkg-config libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev bzip2 dirmngr

    - name: Install Python Tools
      run: |
        pip install --upgrade pip
        pip install cython==0.29.33 setuptools sh
        pip install buildozer==1.5.0

    - name: Build with Buildozer
      run: |
        export FORCE_BUILD_FOR_ROOT=1
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyGame-APK
        path: bin/*.apk
        
